name: Marwan Khelif
description: 
meta_description: "Marwan Khelif, Senior Software Engineer"

baseurl: ''
domain_name: 'http://mkhelif.fr'

aboutPage: false
highlighter: rouge
paginate: 5
paginate_path: 'blog/page:num/'

# Third-parties
google_analytics: 'UA-2859250-3'
disqus_shortname: 'mkhelif'

# Details for the RSS feed generator
url:            'http://mkhelif.fr/'
author:         'Marwan Khelif'
authorTwitter:  'mkhelif'

permalink:       /blog/:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
