# Site
title: Marwan Khelif
email: mkhelif@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.mkhelif.fr/" # the base hostname & protocol for your site

# Configuration
markdown: kramdown
highlighter: pygments
paginate: 20
google_analytics: 'UA-2859250-3'
disqus_shortname: 'mkhelif'

author:         'Marwan Khelif'
authorTwitter:  'mkhelif'
permalink:       /:year/:title/
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

# Social
twitter_username: mkhelif
github_username:  mkhelif
